@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jul 17 20:55:27 +0800 2024
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test_cpu_behav -key {Behavioral:sim_1:Functional:test_cpu} -tclbatch test_cpu.tcl -view F:/Learning/2024summer/vivado/MIPS_Pipeline/Pipeline/test_cpu_behav.wcfg -log simulate.log"
call xsim  test_cpu_behav -key {Behavioral:sim_1:Functional:test_cpu} -tclbatch test_cpu.tcl -view F:/Learning/2024summer/vivado/MIPS_Pipeline/Pipeline/test_cpu_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
